# -*- coding: utf-8 -*-
"""BMI.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1kmy8O-q6c4iV7cdU4imnMjB_2vWoioZo
"""

#Description: This program uses python to calculate an individual's Body Mass Index (BMI)
#BMI is a convenient rule of thumb used to broadly categorize: underweight, normal weight, overweight, obese 
#based on tissue max and height

#A common use of the BMI is to assess how far an individual's body weight departs from what is normal for a person's height
#overweight and obese individuals are at an increased risk for some diseases e.g., sleep apnea, hypertension, type-2 diabetes, stroke, infertility

#Enter weight and height 

weight = float(input("Please enter your weight (lbs): "))
print(" ")
height = float(input("Please enter your height (inches): "))
print(" ")
#Calculate the individual's BMI
h2 = height ** 2 
w = weight
#Calculate the BMI of an individual in U.S. units using the BMI formula
BMI = (w/h2) * 703
BMI = round(BMI, 2)


#Show the indivudals BMI
print("Your Body Mass Index (BMI) is:", BMI)
print(" ")

#Print the individuals results based on the commonly used BMI ranges in North America and Europe for 
#individuals aged 21 and up
if BMI > 0:
  if BMI < 16:
    print("You are severely underweight")
  elif BMI < 17:
    print("You are moderately underweight")
  elif BMI < 18.5:
    print("You are underweight")
  elif BMI < 25:
    print("You are healthy")
  elif BMI < 30:
    print("You are overweight")
  elif BMI < 35:
    print("You are moderately obese")
  elif BMI <= 40:
    print("You are severely obese")
  elif BMI > 40:
    print("You are morbidly obese")
  
else:
  print("The information that you put in is incorrect")

print(" ")
#Calculate the healthy weight of an individual in U.S. units using reversing the BMI formula
#w = (BMI/703) * h2
if 18.5 < BMI < 25:
  print("You are in great shape!")
  
elif BMI < 18.5:
  delta_BMI = 25 - BMI 
  
  w = (delta_BMI/703) * h2
  delta_BMI = round(delta_BMI, 2)
  w = round(w, 2)
  print("You need to gain " + str(w) + "lbs")
  
elif BMI > 25:
  delta_BMI = BMI - 25
  w = (delta_BMI/703) * h2
  delta_BMI = round(delta_BMI, 2)
  w = round(w, 2)
  print("You are off by " + str(delta_BMI) + " from a healthy BMI" + ", which is about " + str(w) + " lbs.")
  
#Body Fat %
print(" ")
age = int(input("What is your age: "))
print(" ")
gender = input("What is your gender: ")
print(" ")
gender = gender.lower()
if gender == "male":
  gender_val = 1
else:
  gender_val = 0   

BF = (1.39 * BMI) + (0.16 * age) - (10.34 * gender_val) - 9
BF = round(BF, 2)

if gender == "male":  
  if BF < 5:
    print("You only have essential fat")
  elif BF < 13:
    print("You are an athlete")
  elif BF < 17:
    print("You are physically fit")
  elif BF < 24:
    print("You are average")
  elif BF >= 25:
    print("You are obese")

if gender == "female":  
  if BF < 13:
    print("You only have essential fat")
  elif BF < 20:
    print("You are an athlete")
  elif BF < 24:
    print("You are physically fit")
  elif BF < 31:
    print("You are average")
  elif BF >= 32:
    print("You are obese")

print(" ")
#Show the indivudals Body Fat %
print("Your Body Fat (%) is: " + str(BF) +"%")
print(" ")

delta_BF = BF - 17
delta_BF = round(delta_BF, 2)
#BF = (1.39 * BMI) + (0.16 * age) - (10.34 * gender_val) - 9
#
if gender == "male":
  if BF > 17:
    print("You are off by " + str(delta_BF) + "% BF" + " from a physically fit BF %")
  else:
    print("You are in great shape!")
  #+ ", which is about " + str(w) + " lbs.")
  
